### ISSUE TITLE
Make ADE operations cancellable

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/plugin-ade-manager#12]
It would be nice to have a "Cancel" button in the dialogs of the ADE operations. For examle, to be able to cancel the transformation of an XML schema or the generation of the delete script. I am not sure whether even the registration of an ADE in the database can be cancelled as this might result in an inconsistent database state? Well, would be great if it could also be cancelled.

**Comment by yaozhihang** [comment]
I didn't make the ADE operations in GUI cancelable, because 
a) yes, it can result in an in consistent database state. I didn't find a good solution to make all ADE operation rollbackable, since the JDBC `connection.rollback()` does not work well with DDL scripts.   
b) The ADE operations like registering and removing ADE normally do not take long time.  The "Cancel" is not really needed in practice.

Of course, it would be nice to have cancellable ADE operations. As i mentioned above, i have to first find a way to make them _rollbackable_.

**Comment by clausnagel** [comment]
Ok, I see. My use case was that I loaded an XML schema just for testing purposes. This schema imports quite a large number of external schemas through <xs:import> statements pointing to web URLs. So, the external schemas were loaded over the internet, which took quite some time. That's when I thought a cancel button would be nice.

But all good, I agree with your priorities. Maybe we can leave this issue open and revisit it whenever suitable.
