### ISSUE TITLE
gml:SurfaceProperty is not mapped to geometry but to text/clob

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/plugin-ade-manager#21]

**Comment by clausnagel** [comment]
My bad. Was using gml:SurfaceArrayProperty instead of gml:SurfaceProperty.

**Comment by BudiHeri** [comment]
Hi, I am recently encounter this issue while trying to register the testADE into the database. 
![image](https://github.com/user-attachments/assets/515647d2-773b-4922-a5bc-ff27a7f9314e)

As you can see, all the geometry column except the multicurve is not mapped as it corresponding geometry.

It also happen to my actual ADE as shown below
![image](https://github.com/user-attachments/assets/6e4e3fd1-66e1-4082-820d-35927faee677)

**Comment by yaozhihang** [comment]
@BudiHeri This is an intentional design of the table mapping. In 3DCityDB v4, all surface-based geometries are centrally stored in the `surface_geometry` table. Each surface-based geometry property is mapped to a foreign key column (in your case "lod1surface_id") pointing to the `surface_geometry` table.
